export default abstract class UpdateEvents {
    public static MAIN_CHECK_FOR_UPDATES = 'CHECK_FOR_UPDATES';
    public static MAIN_DOWNLOAD_UPDATE = 'DOWNLOAD_UPDATE';
    public static MAIN_ABORT_DOWNLOAD_UPDATE = 'ABORT_DOWNLOAD_UPDATE';
    public static MAIN_RESTART_AND_INSTALL_UPDATE = 'INSTALL_UPDATE';
    
    public static RENDERER_SEARCHING_FOR_UPDATES = 'SEARCHING_FOR_UPDATES';
    public static RENDERER_UPDATE_FOUND = 'UPDATE_FOUND';
    public static RENDERER_NO_NEW_VERSION_FOUND = 'NO_NEW_VERSION_FOUND';
    public static RENDERER_DOWNLOAD_CANCELED = 'UPDATE_CANCELED';
    public static RENDERER_DOWNLOADING_UPDATE = 'UPDATE_DOWNLOADING_UPDATE';
    public static RENDERER_PROGRESS_UPDATE = 'PROGRESS_UPDATE';
    public static RENDERER_DOWNLOAD_FINISHED = 'UPDATE_DOWNLOAD_FINISHED';
    public static RENDERER_UPDATE_ERROR = 'UPDATE_ERROR';
}