export default abstract class UpdateEvents {
    public static UPDATE_CHECK_FOR_UPDATES = 'CHECK_FOR_UPDATES';
    public static UPDATE_UPDATE_FOUND = 'UPDATE_FOUND';
    public static UPDATE_DOWNLOAD_UPDATE = 'DOWNLOAD_UPDATE';
    public static UPDATE_ABORT_DOWNLOAD_UPDATE = 'ABORT_DOWNLOAD_UPDATE';
    public static UPDATE_PROGRESS_UPDATE = 'PROGRESS_UPDATE';
    public static UPDATE_DOWNLOAD_FINISHED = 'UPDATE_DOWNLOAD_FINISHED';
    public static UPDATE_RESTART_AND_INSTALL_UPDATE = 'INSTALL_UPDATE';
}